openapi: 3.0.0
info:
  title: Sample API
  description: This is a sample API documentation
  version: 1.0.0
servers:
  - url: http://api.example.com/v1
    description: Production server
paths:
  /users:
    get:
      summary: Get all users
      description: Retrieve a list of all users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: The user ID
                    name:
                      type: string
                      description: The user's name
                    email:
                      type: string
                      description: The user's email
  /posts:
    get:
      summary: Get all posts
      description: Retrieve a list of all posts with their authors
      responses:
        '200':
          description: A list of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: The post ID
                    title:
                      type: string
                      description: The post title
                    content:
                      type: string
                      description: The post content
                    published:
                      type: boolean
                      description: Whether the post is published
                    authorId:
                      type: integer
                      description: The ID of the post author
                    author:
                      type: object
                      description: The author information
                      properties:
                        id:
                          type: integer
                          description: The author ID
                        name:
                          type: string
                          description: The author name
                        email:
                          type: string
                          description: The author email
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
    post:
      summary: Create a new post
      description: Create a new post with the provided information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - content
                - authorId
              properties:
                title:
                  type: string
                  description: The title of the post
                content:
                  type: string
                  description: The content of the post
                authorId:
                  type: integer
                  description: The ID of the post author
      responses:
        '201':
          description: Post created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The created post ID
                  title:
                    type: string
                    description: The post title
                  content:
                    type: string
                    description: The post content
                  published:
                    type: boolean
                    description: Whether the post is published
                  authorId:
                    type: integer
                    description: The ID of the post author 